# Generated by Django 3.2.3 on 2021-10-09 12:10

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='num_of_passengers',
            field=models.PositiveSmallIntegerField(validators=[cars.models.validate_num_of_passangers]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year_of_production',
            field=models.PositiveSmallIntegerField(validators=[cars.models.validate_year_of_production]),
        ),
    ]
