# Generated by Django 3.2.3 on 2021-10-09 12:44

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211009_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_engine_power',
            field=models.PositiveSmallIntegerField(validators=[cars.models.grater_than_zero]),
        ),
    ]
